package examples.enums;

public enum NotificationType {
    BOOKING_CONFIRMATION,
    PAYMENT_RECEIPT,
    FLIGHT_DELAY,
    GATE_CHANGE,
    FLIGHT_CANCELLATION,
    CHECKIN_REMINDER,
    BOARDING_REMINDER,
    MODIFICATION_CONFIRMATION,
    CANCELLATION_CONFIRMATION,
    REFUND_INITIATED,
    REFUND_COMPLETED
}